### ISSUE TITLE
The application must be able to detect a single person in images.

### ISSUE THREAD

**Issue by Jasperkroes** [egedebruin/Trackscape#2]
When given an image the application should give back that it detects a person and where the person is  found. The application should have a way of pointing out where the person is found.

DoD:
The implemented method can detecta person in the image below.
[Insert the image here]
It should correctly be shown where the person is found.
Code should be tested and have **100% branch coverage**

**Comment by lisv** [comment]
Detecting single persons with available libraries did not work as good as we had hoped (because they used different not-fitting training sets). However, we decided that it is not crucial to know where each person is, we just need to know when they are moving/doing something and when they are standing still. So therefore we implemented the measure of activity with background subtraction.
